// This file is auto-generated by `gulp icons`.
// To change the icons, edit the SVG files in `src/lib/icons/svg`.

export type CursorIconMeta = {
  hotspotX: number;
  hotspotY: number;
  viewBoxMinX: number;
  viewBoxMinY: number;
  viewBoxWidth: number;
  viewBoxHeight: number;
};

export function getArrowBottomCursor(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"white\" fill-opacity=\"0.5\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 7 L 93 7 L 50 79 z\"/>\n</svg>";
}

export function getArrowBottomCursorMeta(): CursorIconMeta {
  return {"hotspotX":50,"hotspotY":86,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":100,"viewBoxHeight":86};
}

export function getArrowBottom(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"rgb(242, 242, 76)\" fill-opacity=\"1\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 7 L 93 7 L 50 79 z\"/>\n</svg>";
}

export function getArrowBottomActive(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"rgb(255, 255, 0)\" fill-opacity=\"1\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 7 L 93 7 L 50 79 z\"/>\n</svg>";
}

export function getArrowDown(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 6 10\">\n  <path fill=\"currentColor\" d=\"M 0 6 L 2 6 L 2 0 L 4 0 L 4 6 L 6 6 L 3 10 z\"/>\n</svg>";
}

export function getArrowDownCursor(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"#f9f9f9\" stroke=\"#000\" viewBox=\"0 0 3.9687499 3.96875\">\n  <path stroke-width=\"0.318611\" d=\"m 1.1578161,0.21695335 c -0.061702,-0.0329161 -0.81488983,-0.0133494 -0.81488983,-0.0133494 0,0 0.54265514,0.55608717 0.93827003,0.96284295 0.4433991,0.4558857 0.4777944,0.8151048 0.4777944,0.8151048 H 0.5130859 l 1.6505985,1.7274342 1.434036,-1.7247007 c -0.534692,-0.00674 -0.7326378,0.00633 -1.0334189,0.013349 0,0 -0.1208928,-1.09485632 -1.4064854,-1.78068085 z\" />\n</svg>";
}

export function getArrowDownCursorMeta(): CursorIconMeta {
  return {"hotspotX":2.1636844,"hotspotY":3.70982115,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":3.9687499,"viewBoxHeight":3.96875};
}

export function getArrowLeftAndRight(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 61\">\n  <path fill=\"white\" stroke=\"black\" stroke-width=\"6\" d=\"M 7 30 L 30 7 L 30 20 L 70 20 L 70 7 L 93 30 L 70 54 L 70 40 L 30 40 L 30 54 z\"/>\n</svg>";
}

export function getArrowLeftAndRightMeta(): CursorIconMeta {
  return {"hotspotX":50,"hotspotY":33.5,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":100,"viewBoxHeight":61};
}

export function getArrowLeft(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 61\">\n  <path fill=\"white\" stroke=\"black\" stroke-width=\"6\" d=\"M 7 20 L 60 20 L 60 7 L 93 30 L 60 55 L 60 40 L 7 40 z\" />\n</svg>";
}

export function getArrowLeftMeta(): CursorIconMeta {
  return {"hotspotX":100,"hotspotY":30.5,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":100,"viewBoxHeight":61};
}

export function getArrowRight(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 61\">\n  <path fill=\"white\" stroke=\"black\" stroke-width=\"6\" d=\"M 7 30 L 40 7 L 40 20 L 93 20 L 93 40 L 40 40 L 40 54 z\"/>\n</svg>";
}

export function getArrowRightMeta(): CursorIconMeta {
  return {"hotspotX":0,"hotspotY":30.5,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":100,"viewBoxHeight":61};
}

export function getArrowTopAndBottom(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 90 110\">\n  <path fill=\"white\" stroke=\"black\" stroke-width=\"6\" d=\"M 7 50 L 45 7 L 83 50 z\"/>\n  <path fill=\"white\" stroke=\"black\" stroke-width=\"6\" d=\"M 7 60 L 45 103 L 83 60 z\"/>\n</svg>";
}

export function getArrowTopAndBottomMeta(): CursorIconMeta {
  return {"hotspotX":45,"hotspotY":55,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":90,"viewBoxHeight":110};
}

export function getArrowTopCursor(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"white\" fill-opacity=\"0.7\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 79 L 50 7 L 93 79 z\"/>\n</svg>";
}

export function getArrowTopCursorMeta(): CursorIconMeta {
  return {"hotspotX":50,"hotspotY":0,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":100,"viewBoxHeight":86};
}

export function getArrowTop(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"rgb(242, 242, 76)\" fill-opacity=\"1\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 79 L 50 7 L 93 79 z\"/>\n</svg>";
}

export function getArrowTopActive(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 86\">\n  <path fill=\"rgb(255, 255, 0)\" fill-opacity=\"1\" stroke=\"black\" stroke-width=\"7\" d=\"M 7 79 L 50 7 L 93 79 z\"/>\n</svg>";
}

export function getArrowUp(): string {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 6 10\">\n  <path fill=\"currentColor\" d=\"M 0 4 L 3 0 L 6 4 L 4 4 L 4 10 L 2 10 L 2 4 z\"/>\n</svg>";
}

export function getArrowUpCursor(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"#f9f9f9\" stroke=\"#000\" viewBox=\"0 0 3.9687499 3.96875\">\n  <path stroke-width=\"0.318611\" d=\"m 2.7893699,3.7809852 c 0.061702,0.032916 0.8148899,0.013349 0.8148899,0.013349 0,0 -0.5426551,-0.5560871 -0.9382701,-0.9628429 C 2.2225906,2.375606 2.1881953,2.0163869 2.1881953,2.0163869 H 3.4341002 L 1.7835016,0.28895256 0.34946563,2.0136534 c 0.534692,0.00674 0.73263777,-0.00633 1.03341887,-0.013349 0,0 0.1208928,1.0948563 1.4064854,1.7806808 z\" />\n</svg>";
}

export function getArrowUpCursorMeta(): CursorIconMeta {
  return {"hotspotX":1.7835016,"hotspotY":0.28895256,"viewBoxMinX":0,"viewBoxMinY":0,"viewBoxWidth":3.9687499,"viewBoxHeight":3.96875};
}

export function getRefreshIcon(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 10\">\n  <polyline points=\"6.5 4 8.5 4 8.5 2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <path d=\"M8.5 4 L 7 2.5 A 3 3 0 0 0 2.5 2.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <polyline points=\"3.5 6 1.5 6 1.5 8\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <path d=\"M1.5 6 L 2.5 7 A 3 3 0 0 0 7 7\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n</svg>";
}

export function getTableIcon(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 10\">\n  <rect x=\"0.5\" y=\"0.5\" width=\"9\" height=\"9\" rx=\"1\" ry=\"1\" stroke=\"currentColor\" stroke-width=\"0.5\" fill=\"none\" />\n  <line x1=\"0.5\" y1=\"3.3\" x2=\"9.5\" y2=\"3.3\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <line x1=\"0.5\" y1=\"6.6\" x2=\"9.5\" y2=\"6.6\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <line x1=\"3.3\" y1=\"0.5\" x2=\"3.3\" y2=\"9.5\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <line x1=\"6.6\" y1=\"0.5\" x2=\"6.6\" y2=\"9.5\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n</svg>";
}

export function getExpandToolbarIcon(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 -0.5 6 6\">\n  <polyline points=\"1 0.75 3 2.75 1 4.75\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.25\"/>\n  <polyline points=\"3 0.75 5 2.75 3 4.75\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.25\"/>\n</svg>";
}

export function getCollapseToolbarIcon(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 -0.5 6 6\">\n  <polyline points=\"3 0.75 1 2.75 3 4.75\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.25\"/>\n  <polyline points=\"5 0.75 3 2.75 5 4.75\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.25\"/>\n</svg>";
}

export function getResetIcon(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 10\">\n  <g transform=\"scale(1,0.833) translate(0,1.2)\">\n    <path d=\"M8 4 A4 3.5 0 1 1 2 4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n    <polyline points=\"3 5.5 2 4 0 4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n    <path d=\"M5 1 L 5 6.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  </g>\n</svg>";
}

export function getDownloadButton(): string {
  return "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 10\">\n  <path fill=\"currentColor\" d=\"M 4.65 7 L 4.65 1.4 L 5.25 1.4 L 5.25 7 z\"/>\n  <polyline points=\"2.07 5.00 4.93 7.14 7.79 5.00\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.5\"/>\n  <path fill=\"currentColor\" d=\"M 2 8.5 L 8 8.5 L 8 9 L 2 9 z\"/>\n</svg>";
}

export function getZoomButton(): string {
  return "<?xml version=\"1.0\" encoding=\"utf-8\"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n<svg width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 17C13.866 17 17 13.866 17 10C17 6.13401 13.866 3 10 3C6.13401 3 3 6.13401 3 10C3 13.866 6.13401 17 10 17Z\" stroke=\"#000000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20.9992 21L14.9492 14.95\" stroke=\"#000000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M6 10H14\" stroke=\"#000000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M10 6V14\" stroke=\"#000000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>";
}

export function getPanButton(): string {
  return "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n<svg fill=\"#000000\" height=\"800px\" width=\"800px\" version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" \n\t viewBox=\"0 0 485 485\" xml:space=\"preserve\">\n<g>\n\t<path d=\"M382.5,69.429c-7.441,0-14.5,1.646-20.852,4.573c-4.309-23.218-24.7-40.859-49.148-40.859\n\t\tc-7.68,0-14.958,1.744-21.467,4.852C285.641,16.205,265.932,0,242.5,0c-23.432,0-43.141,16.206-48.533,37.995\n\t\tc-6.508-3.107-13.787-4.852-21.467-4.852c-27.57,0-50,22.43-50,50v122.222c-6.129-2.686-12.891-4.187-20-4.187\n\t\tc-27.57,0-50,22.43-50,50V354c0,72.233,58.766,131,131,131h118c72.233,0,131-58.767,131-131V119.429\n\t\tC432.5,91.858,410.07,69.429,382.5,69.429z M402.5,354c0,55.691-45.309,101-101,101h-118c-55.691,0-101-45.309-101-101V251.178\n\t\tc0-11.028,8.972-20,20-20s20,8.972,20,20v80h30V83.143c0-11.028,8.972-20,20-20s20,8.972,20,20v158.035h30V50\n\t\tc0-11.028,8.972-20,20-20c11.028,0,20,8.972,20,20v191.178h30V83.143c0-11.028,8.972-20,20-20s20,8.972,20,20v158.035h30v-121.75\n\t\tc0-11.028,8.972-20,20-20s20,8.972,20,20V354z\"/>\n</g>\n</svg>";
}
