const fs = require("fs");
const path = require("path");

const ICON_SVG_DIR = path.resolve(__dirname, "../src/lib/icons/svg");
const OUTPUT_FILE = path.resolve(__dirname, "../src/lib/icons/icons.ts");

const ICON_MANIFEST = [
  ["getArrowBottomCursor", "arrow-bottom-cursor.svg"],
  ["getArrowBottom", "arrow-bottom.svg"],
  ["getArrowBottomActive", "arrow-bottom-active.svg"],
  ["getArrowDown", "arrow-down.svg"],
  ["getArrowDownCursor", "arrow-down-cursor.svg"],
  ["getArrowLeftAndRight", "arrow-left-and-right.svg"],
  ["getArrowLeft", "arrow-left.svg"],
  ["getArrowRight", "arrow-right.svg"],
  ["getArrowTopAndBottom", "arrow-top-and-bottom.svg"],
  ["getArrowTopCursor", "arrow-top-cursor.svg"],
  ["getArrowTop", "arrow-top.svg"],
  ["getArrowTopActive", "arrow-top-active.svg"],
  ["getArrowUp", "arrow-up.svg"],
  ["getArrowUpCursor", "arrow-up-cursor.svg"],
  ["getRefreshIcon", "refresh.svg"],
  ["getTableIcon", "table.svg"],
  ["getExpandToolbarIcon", "toolbar_expand.svg"],
  ["getCollapseToolbarIcon", "toolbar_collapse.svg"],
  ["getResetIcon", "reset.svg"],
  ["getDownloadButton", "download.svg"],
];

function parseCursorMeta(svg) {
  const hotspotMatch = svg.match(
    /<!--\s*spcd3-cursor-hotspot:\s*([^\s]+)\s+([^\s]+)\s*-->/,
  );
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);

  if (!hotspotMatch || !viewBoxMatch) {
    return null;
  }

  const [minX, minY, width, height] = viewBoxMatch[1]
    .trim()
    .split(/\s+/)
    .map(Number);

  return {
    hotspotX: Number(hotspotMatch[1]),
    hotspotY: Number(hotspotMatch[2]),
    viewBoxMinX: minX,
    viewBoxMinY: minY,
    viewBoxWidth: width,
    viewBoxHeight: height,
  };
}

function readSvg(filename) {
  const filePath = path.join(ICON_SVG_DIR, filename);
  const svg = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n").trim();
  const cleanSvg = svg
    .replace(/<!--\s*spcd3-cursor-hotspot:[\s\S]*?-->\s*/g, "")
    .trim();

  if (
    filename === "toolbar_expand.svg" ||
    filename === "toolbar_collapse.svg"
  ) {
    return {
      svg: cleanSvg.replace('viewBox="0 0 6 6"', 'viewBox="0 -0.5 6 6"'),
      cursorMeta: null,
    };
  }

  return {
    svg: cleanSvg,
    cursorMeta: parseCursorMeta(svg),
  };
}

function createIconModule() {
  const lines = [
    "// This file is auto-generated by `gulp icons`.",
    "// To change the icons, edit the SVG files in `src/lib/icons/svg`.",
    "",
    "export type CursorIconMeta = {",
    "  hotspotX: number;",
    "  hotspotY: number;",
    "  viewBoxMinX: number;",
    "  viewBoxMinY: number;",
    "  viewBoxWidth: number;",
    "  viewBoxHeight: number;",
    "};",
    "",
  ];

  ICON_MANIFEST.forEach(([exportName, filename]) => {
    const { svg, cursorMeta } = readSvg(filename);
    lines.push(`export function ${exportName}(): string {`);
    lines.push(`  return ${JSON.stringify(svg)};`);
    lines.push("}");
    lines.push("");

    if (cursorMeta) {
      lines.push(
        `export function ${exportName}Meta(): CursorIconMeta {`,
      );
      lines.push(`  return ${JSON.stringify(cursorMeta)};`);
      lines.push("}");
      lines.push("");
    }
  });

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateIcons(done) {
  fs.writeFileSync(OUTPUT_FILE, createIconModule());
  done();
}

module.exports = { generateIcons };
