const fs = require("fs");
const path = require("path");

const ICON_SVG_DIR = path.resolve(__dirname, "../src/lib/icons/svg");
const OUTPUT_FILE = path.resolve(__dirname, "../src/lib/icons/icons.ts");

const ICON_MANIFEST = [
  ["getArrowBottomCursor", "arrow-bottom-cursor.svg"],
  ["getArrowBottom", "arrow-bottom.svg"],
  ["getArrowBottomActive", "arrow-bottom-active.svg"],
  ["getArrowDown", "arrow-down.svg"],
  ["getArrowDownCursor", "arrow-down-cursor.svg"],
  ["getArrowLeftAndRight", "arrow-left-and-right.svg"],
  ["getArrowLeft", "arrow-left.svg"],
  ["getArrowRight", "arrow-right.svg"],
  ["getArrowTopAndBottom", "arrow-top-and-bottom.svg"],
  ["getArrowTopCursor", "arrow-top-cursor.svg"],
  ["getArrowTop", "arrow-top.svg"],
  ["getArrowTopActive", "arrow-top-active.svg"],
  ["getArrowUp", "arrow-up.svg"],
  ["getArrowUpCursor", "arrow-up-cursor.svg"],
  ["getRefreshIcon", "refresh.svg"],
  ["getTableIcon", "table.svg"],
  ["getExpandToolbarIcon", "toolbar_expand.svg"],
  ["getCollapseToolbarIcon", "toolbar_collapse.svg"],
  ["getResetIcon", "reset.svg"],
  ["getDownloadButton", "download.svg"],
];

function readSvg(filename) {
  const filePath = path.join(ICON_SVG_DIR, filename);
  const svg = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n").trim();

  if (filename === "toolbar_expand.svg" || filename === "toolbar_collapse.svg") {
    return svg.replace('viewBox="0 0 6 6"', 'viewBox="0 -0.5 6 6"');
  }

  return svg;
}

function createIconModule() {
  const lines = [
    "// This file is auto-generated by `gulp icons`.",
    "// Edit the SVG files in `src/lib/icons/svg` instead.",
    "",
  ];

  ICON_MANIFEST.forEach(([exportName, filename]) => {
    lines.push(`export function ${exportName}(): string {`);
    lines.push(`  return ${JSON.stringify(readSvg(filename))};`);
    lines.push("}");
    lines.push("");
  });

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateIcons(done) {
  fs.writeFileSync(OUTPUT_FILE, createIconModule());
  done();
}

module.exports = { generateIcons };
